<a href="https://colab.research.google.com/github/kimberlyydanij/python_demo/blob/master/python_11_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 필수 패키지중 하나이다.
- 과학 계산을 위한 대부분의 패키지는 Numpy의 배열 객체를 데이터 교환을 위한 공통언어처럼 사용한다.
- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드 캐스팅 기능을 제공한다.
- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수 이다.
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구이다.
- 선형대수, 난수 생성기등에 사용된다.
- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.

공식문서 https://numpy.org/doc/stable/reference/
문제100 https://github.com/rougier/numpy-100


# 1. 데이터 생성

In [40]:
import numpy as np

In [2]:
a = np.zeros(3)  # 1차원 배열 = 벡터
a

array([0., 0., 0.])

In [3]:
print(a)

[0. 0. 0.]


In [4]:
#처음 객체들은 type(), dir()을 해본다.

In [6]:
print(type(a))
print(dir(a))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [10]:
# 1차원 배열(벡터)
a = np.array([1,2,3]) 
a

array([1, 2, 3])

In [20]:
print(type(a))
print(dir(a))
print(len(dir(a)))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [9]:
# 2차원 배열(행렬)
b = np.array([[1,2,],[3,4,]])
b

array([[1, 2],
       [3, 4]])

In [21]:
print(type(b))
print(dir(b))
print(len(dir(b)))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [18]:
# 3차원 배열 이상 (텐서/tensor)
c = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])
c 

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
print(type(c))
print(dir(c))
print(len(dir(c)))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [25]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous이다.
a = np.array([1,'2',3])
print(a)
print(type(a))
print(type(a[0]))

['1' '2' '3']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [28]:
b = np.array(['a',1,True])
print(b)
print(type(b))
b

['a' '1' 'True']
<class 'numpy.ndarray'>


array(['a', '1', 'True'], dtype='<U21')

In [30]:
c = np.array([1, True, 2, False])
print(c)
print(type(c))
c
print(type(c[0]))

[1 1 2 0]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


#### np.zeros
- tuple로 인자를 넣으면 그대로 모양을 만든다.
- (2,3) : 2행 3열 행렬을 만든다.
- zeros는 0으로 값을 모두 채운다.
- a = np.zeros((2,3))
- a = np.zeros([2,3])

In [31]:
a = np.zeros([2,3])
a


array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
c = np.zeros([2,3,2])
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

# np.eye
- eye는 단위행렬
- 숫자만 사용할 수 있다.

In [34]:
# 인자값이 1개 이면 행과 열이 같다.
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# eye는 행과 열의 크기를 지정할 수 있다.
# 3행 2열 행렬 생성
b = np.eye(3,2)
b

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [38]:
# 크기(1)가 시작되는 위치를 지정할 수 있다.
c = np.eye(3, 4,k=1)
c

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.identify
-  수학에서 단위행렬은 영어로 identify matrix
-  크기 한개만 지정해서 생성할 수 있다.

In [43]:
#type error 발생
#인자 하나만 지정할 수 있다.
d = np.identify(3,2)
d

AttributeError: ignored

### np.full
- 지정한 크기의 배열을 생성하고 채울값을 지정한다.
- 2행 2열의 배열 생성후 2로 채워준다.
  np.full((2,2),1)
  

In [44]:
a = np.full((2,2), 1)
a


array([[1, 1],
       [1, 1]])

In [46]:
# 1행 3열의 배열 생성 후 4로 채워준다
b = np.full(3,4)
b

array([4, 4, 4])

In [48]:
c = np.full((2,2),[1,2])
c

array([[1, 2],
       [1, 2]])

In [51]:
d = np.full()
d

TypeError: ignored

### np.empty
- 배열을 생성하고 초기화를 지정하지 않는다.
- 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.

In [49]:
a = np.empty(3)
a

array([1., 1., 1.])

In [53]:
# zeros해서 생성한 배열이 있으면 배열의 값을 0으로 채워준다.
k = np.zeros((2,3))
k

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
b = np.empty((2,3))
b

array([[3.34479043e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [57]:
c = np.empty((2,5))
c

array([[3.31723184e-316, 1.77863633e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [7.86642629e-067, 4.99047050e+174, 4.71290644e-090,
        1.56056501e+161, 4.75719885e-315]])

### np.ones
- 배열의 값을 1로 초기화 해준다.


In [58]:
a = np.ones(3)
a

array([1., 1., 1.])

In [59]:
# 1행 3열의 배열 생성 후 모든 값을 1로 채운다
a = np.ones(3)
a

array([1., 1., 1.])

In [61]:
#b = np.ones((2,3))
b = np.ones([2,3])
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
c = np.empty((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [65]:
e = np.eye(3,4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [66]:
d = np.empty((3,4))
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [67]:
e = np.full((3,4),0)
e

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [68]:
f = np.empty((3,4))
f

array([[3.27173907e-316, 6.79038653e-313, 2.37663529e-312,
        2.16443571e-312],
       [2.29175545e-312, 8.48798317e-313, 1.08221785e-312,
        1.10343781e-312],
       [9.33678148e-313, 8.70018275e-313, 2.14321575e-312,
        1.46030983e-319]])

### _like
- _like 가 붙으면 shape가 같게 만들어진다.
- 연산하기 위해서 shape를 맞춰야 하는 경우가 있다.


In [69]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
a.shape

(2, 3)

In [72]:
b = np.empty_like(a)
b

array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [73]:
#valueError
c+b

array([[4.60718242e+18, 4.60718242e+18, 4.60718242e+18],
       [4.60718242e+18, 4.60718242e+18, 4.60718242e+18]])

### linspace
- 동등한 간격으로 값을 생성한다
- 0부터 49까지 50개가 생성된다면, 세번째 num인자 값이 생략되어 있으므로 start와 end 계산해서 default 50이 생성된다.  

  linspace(start,end,num)  
  linspace(0,49)  #num=50

In [74]:
a = np.linspace(0, 49)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [75]:
b = np.linspace(1,5)
b

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [76]:
len(b)

50

In [77]:
# 1부터 10까지 3개의 요소를 생성한다.
# 기본은 endpoint = True로 설정되어 있기 때문에, 10이 포함되어 있다.
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [78]:
# 1부터 10미만 사이에서 3개의 요소를 생성한다.
# endpoint = False로 설정되어 있으므로 10이 포함되어 있지 않다.
np.linspace(1,10,3, endpoint=False)

array([1., 4., 7.])

### logspace
- linspace와 비슷하다.
- log scale을 사용하는 차이가 있다.  
- 1부터 50까지 사이에 10개의 요소를 생성한다.
  np.logspace(1, 50, 10)

In [79]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

### *dtype*
- numpy는 c언어를 기반으로 해서 만들었기 때문에 c의 데이터 타입을 차용할 수 있다,

In [80]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [83]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [84]:
b = np.array([1,2,3], dtype=np.int8)
b

array([1, 2, 3], dtype=int8)

In [86]:
#np.int8은 -128 ~ 127 사이의 값을 저장할 수 있다.
c = np.array([-127, -128, 127, 2, 3, -127, -128, 127], dtype=np.int8)
c

array([-127, -128,  127,    2,    3, -127, -128,  127], dtype=int8)

In [88]:
# int는 python의 int를 사용한다.
d = np.array([127, 2, 3, -127, -128], dtype=int)
d

array([ 127,    2,    3, -127, -128])

In [89]:
type(d[0])

numpy.int64

In [90]:
?sum

In [91]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [92]:
np.lookfor('sum')

Search results for 'sum'
------------------------
numpy.sum
    Sum of array elements over a given axis.
numpy.cumsum
    Return the cumulative sum of the elements along a given axis.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nansum
    Return the sum of array elements over a given axis treating Not a
numpy.nancumsum
    Return the cumulative sum of array elements over a given axis treating Not a
numpy.einsum_path
    Evaluates the lowest cost contraction order for an einsum expression by
numpy.trace
    Return the sum along diagonals of the array.
numpy.ma.sum
    Return the sum of the array elements over the given axis.
numpy.Bytes0.sum
    Scalar method identical to the corresponding array attribute.
numpy.polyadd
    Find the sum of two polynomials.
numpy.ma.cumsum
    Return the cumulative sum of the array elements over the given axis.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.Bytes0.cumsum
    Scal

In [95]:
a.ndim

1

In [93]:
# 데이터 타입을 알려준다
a.dtype

dtype('int64')

In [94]:
# 요소의 개수를 알려준다.
# shape로도 알 수 있다.
a. size

3

In [96]:
# 요소당 byte 수를 알려준다.
a.itemsize

8

In [ ]:
# 2. numpy와 python의 속도 차이

In [97]:
np.arange(10) #range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
# numpy를 이용한 계산
%time np.sum(np.arange(1000000000))  #7.5초  // 넘파이가 더 빠름

CPU times: user 1.88 s, sys: 5.12 s, total: 7 s
Wall time: 7.05 s


499999999500000000

In [104]:
%time np.sum(np.arange(1000000000))  #5.2초 // 같은 넘파이라도 방법에 따라 속도 차이가 남

CPU times: user 2.49 s, sys: 2.67 s, total: 5.15 s
Wall time: 5.2 s


499999999500000000

값이 작을때는 속도가 비슷하다.
값이 커지면 속도 차이가 난다.

In [103]:
# python을 이용한 계산
%time sum(range(1000000000))  # 21.8초

CPU times: user 21.6 s, sys: 0 ns, total: 21.6 s
Wall time: 21.8 s


499999999500000000

### 3. COPY
※ 대입문 6가지  
a = 1   
a = b = 1  
a,b = 1, 2  
a, *b = 1, 2, 3  
a += 1    
global, nonlocal

##pyrhon 에서 copy

In [6]:
a = [1, 2, 3]  #heteroneneous, sequence, mutablea

In [7]:
b = a

In [8]:
b

[1, 2, 3]

In [9]:
a is b #메모리 주소 비교

True

In [10]:
#a와 b과 메모리 주소를 굥유 
#b의 값을 변경하면 a의 값도 같이 변경됨
b[0] = 7

In [11]:
b

[7, 2, 3]

In [12]:
a

[7, 2, 3]

list copy

In [15]:
a = [1, 2, 3]

In [16]:
# copy()는 똑같은 값만 가지고 메모리는 공유하지 않는다.
b = a.copy()

In [17]:
b

[1, 2, 3]

In [18]:
a is b

False

In [19]:
id(a)

139810000753664

In [20]:
id(b)

139810000754432

In [21]:
a == b

True

In [22]:
b[0] = 8
print(a)
print(b)

[1, 2, 3]
[8, 2, 3]


In [23]:
print(a is b)
print(a == b)

False
False


list가 2차원일 때

In [24]:
a = [[1,2,3]]

In [25]:
type(a)

list

In [26]:
# shallow copy
b = a.copy()

In [27]:
print(a is b)
print(a == b)

False
True


In [28]:
print(a[0] is b[0])
print(a[0] == b[0])

True
True


list deep copy

In [29]:
import copy

In [30]:
a = [[1,2,3]]
b = copy.deepcopy(a)

In [31]:
print(a)
print(b)

[[1, 2, 3]]
[[1, 2, 3]]


In [33]:
print(a is b)
print(a == b)
print(a[0] is b[0])
print(a[0] == b[0])

False
True
False
True


[:]는 전체라는 뜻이다.
슬라이싱 방식으로 1차 리스트일때는 재할당 하면 deepcopy가 된다. 슬라이싱 2차 리스트 이상인 경우  shallow copy 가 발생한다.

In [34]:
a = [1, 2, 3]
b = a[:]      # a[1] 인덱스  a[1:] 슬라이스
print(a is b)
print(a == b)
b[0] = 7
print(a is b)
print(a == b)

False
True
False
False


※ python의 기본  copy 는  shallow copy 이다.

numpy의 copy

In [41]:
a = b = np.array([1, 2, 3])

In [37]:
print(a is b)
print(a == b)

False
False


array는 sequence 타입으로 인덱싱과 슬라이싱이 가능하다

In [42]:
a[0] #indexing

1

In [43]:
a[:] #slicing

array([1, 2, 3])

In [46]:
# array는 mutable이다.
# 예외가 몇 가지 있지만 mutable에 가깝다.
a[0] = 100
print(a)
print(b)


[100   2   3]
[100   2   3]


array는 homogeneous, sequence, mutable이다.
array deepcopy

In [49]:
a = np.array([[1, 2, 3]])
# numpy는 기본적으로 deepcopy이다.
b = a.copy()

In [50]:
print(a is b)

False


In [51]:
print(a[0] is b[0])

False


#as 계열
다른 데이터 타입을 가져와서 바꿔서 사용할 때는 as라는 이름이 보통 붙는다.

In [55]:
# python의 list 데이터 타입을 int ndarry로 변환
a = [1, 2, 3] #python list
print(type(a))
print(type(a[0]))
b = np.array(a)
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [56]:
a = [1, 2, 3] #python list
print(type(a))
print(type(a[0]))
b = np.asarray(a)
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [57]:
# python의 list 데이터를  float ndarry로 변환
a = [1, 2, 3] #python list
print(type(a))
print(type(a[0]))
b = np.asfarray(a)
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [61]:
#python의 list 데이터 타입 float 이면 float ndarry 로 변환
#python의 list 데이터 타입 int 이면 int ndarry로 변환
a = [1., 2., 3]
print(type(a))
print(type(a[0]))

b = np.asarray(a)
print(type(b))
print(type(b[0]))

c = np.array(a)
print(type(c))
print(type(c[0]))

<class 'list'>
<class 'float'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


### 5. 값 가져오기

####(1) comma 로 값 가져오기

In [64]:
a = [[1, 2, 3],[4, 5, 6]]  #phtyon
b = np.array([[1, 2, 3],[4, 5, 6]]) #numpy

In [65]:
# 1차원 리스트로 가져온다.
a[0]

[1, 2, 3]

In [66]:
# TypeError 
a[0,1]

TypeError: ignored

In [67]:
#2차원 리스트로 가져온다
a[slice(0, 1)] #0행부터 1행 미만의 데이터를 가져온다

[[1, 2, 3]]

In [69]:
a[slice(0, 2)] #0 행에서부터 2행 미만의 데이터를 가져온다

[[1, 2, 3], [4, 5, 6]]

In [70]:
a[0:2]

[[1, 2, 3], [4, 5, 6]]

numpy는 기본적으로 인덱싱/슬라이싱할때 comma를 사용할 수 있다.

In [72]:
#numpy
#b[행,열]
print(b[0,2])

3


In [73]:
#python
#a[행][열]
print(a[0][2])
print(a[0][-1])

3
3


#### (2) boolean indexing

In [74]:
a = [[1, 2, 3, 4]] #python list
a >3

TypeError: ignored

In [75]:
b = np.array([1, 2, 3, 4])
b

array([1, 2, 3, 4])

array를 scalar와 연산하면 elementwise로 계산한다     
(elementwise : 원소별로 각각 계산이 된다.)

In [77]:
## 원소별로 비교해서 True/False로 계산한다
#1>2,  2>2, 3>2, 4>2
#numpy에서는 가능하고 python에서는 안된다
b>2

array([False, False,  True,  True])

numpy는 indexing slicing 자리에 조건도 쓸 수 있다.
True에 해당되는 값만 가져온다.

In [78]:
#boolean indexing
b[np.array([False, False, True, True])]  #b[1, 2, 3, 4]

array([3, 4])

numpy에서 boolean indexing 조건
- array만 가능하다
- numpy True, False로만 가능하다.
- shape가 맞아야 한다. (개수가 맞을 때만 사용 할 수 있다.
- phtyon에서는 지원하지 않는다.

In [79]:
a = [1, 2, 3, 4]
a[True, True, False, False]

TypeError: ignored

###(3) fancy indexing

In [81]:
b = np.arange(100).reshape(20,5) # reshape(행,열) 배열의 구조 변경
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

인덱싱, 슬라이싱 자리에 괄호를 하나 더 넣으면 fancying indexing  할 수 있다.
여러개를 한번에 인덱싱 할 수 있다.

In [88]:
b[:] #전체를 가져온다. b[:,:]와 같다.
# b[행,열]
print(b[1:3])  # 1행부터 3행 미만의 데이터를 가져온다
print(b[1:3,2:4])  # 1행부터 3행 미만 이면서 2열부터 4열 미만 데이터
print(b[[1,3,5]])  # 1행, 3행, 5행의 데이터를 가져온다.
print(b[[1,3,5],[0,2,4]]) #1행 0열, 3행 2열, 5행 4열

[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 7  8]
 [12 13]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]
[ 5 17 29]


fancying indexing은 인덱싱 기법만 사용할 수 있다.
":"콜론은 슬라이싱 기법이므로 지원하지 않는다.

In [89]:
# Error
b[[2:5]]

SyntaxError: ignored

In [90]:
#0열, 2열, 4열에 해당하는 모든 행을 가져온다.
b[:, [0, 2, 4]]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39],
       [40, 42, 44],
       [45, 47, 49],
       [50, 52, 54],
       [55, 57, 59],
       [60, 62, 64],
       [65, 67, 69],
       [70, 72, 74],
       [75, 77, 79],
       [80, 82, 84],
       [85, 87, 89],
       [90, 92, 94],
       [95, 97, 99]])

In [92]:
# 개수가 같게 지정되야 한다.
b[[1, 3, 4],[0, 2, 1]]  # 정상처리
b[[1, 3, 4],[0,2]]  # index error

IndexError: ignored