<a href="https://colab.research.google.com/github/kimberlyydanij/python_demo/blob/master/python_11_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 필수 패키지중 하나이다.
- 과학 계산을 위한 대부분의 패키지는 Numpy의 배열 객체를 데이터 교환을 위한 공통언어처럼 사용한다.
- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드 캐스팅 기능을 제공한다.
- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수 이다.
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구이다.
- 선형대수, 난수 생성기등에 사용된다.
- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.

공식문서 https://numpy.org/doc/stable/reference/
문제100 https://github.com/rougier/numpy-100


# 1. 데이터 생성

In [1]:
import numpy as np

In [2]:
a = np.zeros(3)  # 1차원 배열 = 벡터
a

array([0., 0., 0.])

In [3]:
print(a)

[0. 0. 0.]


In [4]:
#처음 객체들은 type(), dir()을 해본다.

In [6]:
print(type(a))
print(dir(a))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [10]:
# 1차원 배열(벡터)
a = np.array([1,2,3]) 
a

array([1, 2, 3])

In [20]:
print(type(a))
print(dir(a))
print(len(dir(a)))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [9]:
# 2차원 배열(행렬)
b = np.array([[1,2,],[3,4,]])
b

array([[1, 2],
       [3, 4]])

In [21]:
print(type(b))
print(dir(b))
print(len(dir(b)))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [18]:
# 3차원 배열 이상 (텐서/tensor)
c = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])
c 

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
print(type(c))
print(dir(c))
print(len(dir(c)))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [25]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous이다.
a = np.array([1,'2',3])
print(a)
print(type(a))
print(type(a[0]))

['1' '2' '3']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [28]:
b = np.array(['a',1,True])
print(b)
print(type(b))
b

['a' '1' 'True']
<class 'numpy.ndarray'>


array(['a', '1', 'True'], dtype='<U21')

In [30]:
c = np.array([1, True, 2, False])
print(c)
print(type(c))
c
print(type(c[0]))

[1 1 2 0]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


#### np.zeros
- tuple로 인자를 넣으면 그대로 모양을 만든다.
- (2,3) : 2행 3열 행렬을 만든다.
- zeros는 0으로 값을 모두 채운다.
- a = np.zeros((2,3))
- a = np.zeros([2,3])

In [31]:
a = np.zeros([2,3])
a


array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
c = np.zeros([2,3,2])
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

# np.eye
- eye는 단위행렬
- 숫자만 사용할 수 있다.

In [34]:
# 인자값이 1개 이면 행과 열이 같다.
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# eye는 행과 열의 크기를 지정할 수 있다.
# 3행 2열 행렬 생성
b = np.eye(3,2)
b

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [38]:
# 크기(1)가 시작되는 위치를 지정할 수 있다.
c = np.eye(3, 4,k=1)
c

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.identify
-  수학에서 단위행렬은 영어로 identify matrix
-  크기 한개만 지정해서 생성할 수 있다.

In [43]:
#type error 발생
#인자 하나만 지정할 수 있다.
d = np.identify(3,2)
d

AttributeError: ignored

### np.full
- 지정한 크기의 배열을 생성하고 채울값을 지정한다.
- 2행 2열의 배열 생성후 2로 채워준다.
  np.full((2,2),1)
  

In [44]:
a = np.full((2,2), 1)
a


array([[1, 1],
       [1, 1]])

In [46]:
# 1행 3열의 배열 생성 후 4로 채워준다
b = np.full(3,4)
b

array([4, 4, 4])

In [48]:
c = np.full((2,2),[1,2])
c

array([[1, 2],
       [1, 2]])

In [51]:
d = np.full()
d

TypeError: ignored

### np.empty
- 배열을 생성하고 초기화를 지정하지 않는다.
- 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.

In [49]:
a = np.empty(3)
a

array([1., 1., 1.])

In [53]:
# zeros해서 생성한 배열이 있으면 배열의 값을 0으로 채워준다.
k = np.zeros((2,3))
k

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
b = np.empty((2,3))
b

array([[3.34479043e-316, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [57]:
c = np.empty((2,5))
c

array([[3.31723184e-316, 1.77863633e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [7.86642629e-067, 4.99047050e+174, 4.71290644e-090,
        1.56056501e+161, 4.75719885e-315]])

### np.ones
- 배열의 값을 1로 초기화 해준다.


In [58]:
a = np.ones(3)
a

array([1., 1., 1.])

In [59]:
# 1행 3열의 배열 생성 후 모든 값을 1로 채운다
a = np.ones(3)
a

array([1., 1., 1.])

In [61]:
#b = np.ones((2,3))
b = np.ones([2,3])
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [62]:
c = np.empty((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [65]:
e = np.eye(3,4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [66]:
d = np.empty((3,4))
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [67]:
e = np.full((3,4),0)
e

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [68]:
f = np.empty((3,4))
f

array([[3.27173907e-316, 6.79038653e-313, 2.37663529e-312,
        2.16443571e-312],
       [2.29175545e-312, 8.48798317e-313, 1.08221785e-312,
        1.10343781e-312],
       [9.33678148e-313, 8.70018275e-313, 2.14321575e-312,
        1.46030983e-319]])

### _like
- _like 가 붙으면 shape가 같게 만들어진다.
- 연산하기 위해서 shape를 맞춰야 하는 경우가 있다.


In [69]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
a.shape

(2, 3)

In [72]:
b = np.empty_like(a)
b

array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [73]:
#valueError
c+b

array([[4.60718242e+18, 4.60718242e+18, 4.60718242e+18],
       [4.60718242e+18, 4.60718242e+18, 4.60718242e+18]])

### linspace
- 동등한 간격으로 값을 생성한다
- 0부터 49까지 50개가 생성된다면, 세번째 num인자 값이 생략되어 있으므로 start와 end 계산해서 default 50이 생성된다.  

  linspace(start,end,num)  
  linspace(0,49)  #num=50

In [74]:
a = np.linspace(0, 49)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [75]:
b = np.linspace(1,5)
b

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [76]:
len(b)

50

In [77]:
# 1부터 10까지 3개의 요소를 생성한다.
# 기본은 endpoint = True로 설정되어 있기 때문에, 10이 포함되어 있다.
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [78]:
# 1부터 10미만 사이에서 3개의 요소를 생성한다.
# endpoint = False로 설정되어 있으므로 10이 포함되어 있지 않다.
np.linspace(1,10,3, endpoint=False)

array([1., 4., 7.])

### logspace
- linspace와 비슷하다.
- log scale을 사용하는 차이가 있다.  
- 1부터 50까지 사이에 10개의 요소를 생성한다.
  np.logspace(1, 50, 10)

In [79]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

### *dtype*
- numpy는 c언어를 기반으로 해서 만들었기 때문에 c의 데이터 타입을 차용할 수 있다,

In [80]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [83]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [84]:
b = np.array([1,2,3], dtype=np.int8)
b

array([1, 2, 3], dtype=int8)

In [86]:
#np.int8은 -128 ~ 127 사이의 값을 저장할 수 있다.
c = np.array([-127, -128, 127, 2, 3, -127, -128, 127], dtype=np.int8)
c

array([-127, -128,  127,    2,    3, -127, -128,  127], dtype=int8)

In [88]:
# int는 python의 int를 사용한다.
d = np.array([127, 2, 3, -127, -128], dtype=int)
d

array([ 127,    2,    3, -127, -128])

In [89]:
type(d[0])

numpy.int64