<a href="https://colab.research.google.com/github/kimberlyydanij/python_demo/blob/master/python_22_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

### 버전 확인

In [2]:
# python
import sys
print(sys.version)

!python --version

3.8.16 (default, Dec  7 2022, 01:12:13) 
[GCC 7.5.0]
Python 3.8.16


In [4]:
# numpy
np.__version__

'1.21.6'

In [ ]:
# pandas
pd.__version__

'1.3.5'

In [5]:
# 구글 colab
!pip freeze

absl-py==1.3.0
aeppl==0.0.33
aesara==2.7.9
aiohttp==3.8.3
aiosignal==1.3.1
alabaster==0.7.12
albumentations==1.2.1
altair==4.2.0
appdirs==1.4.4
arviz==0.12.1
astor==0.8.1
astropy==4.3.1
astunparse==1.6.3
async-timeout==4.0.2
atari-py==0.2.9
atomicwrites==1.4.1
attrs==22.1.0
audioread==3.0.0
autograd==1.5
Babel==2.11.0
backcall==0.2.0
beautifulsoup4==4.6.3
bleach==5.0.1
blis==0.7.9
bokeh==2.3.3
branca==0.6.0
bs4==0.0.1
CacheControl==0.12.11
cachetools==5.2.0
catalogue==2.0.8
certifi==2022.9.24
cffi==1.15.1
cftime==1.6.2
chardet==3.0.4
charset-normalizer==2.1.1
click==7.1.2
clikit==0.6.2
cloudpickle==1.5.0
cmake==3.22.6
cmdstanpy==1.0.8
colorcet==3.0.1
colorlover==0.3.0
community==1.0.0b1
confection==0.0.3
cons==0.4.5
contextlib2==0.5.5
convertdate==2.4.0
crashtest==0.3.1
crcmod==1.7
cufflinks==0.17.3
cvxopt==1.3.0
cvxpy==1.2.2
cycler==0.11.0
cymem==2.0.7
Cython==0.29.32
daft==0.0.4
dask==2022.2.1
datascience==0.17.5
db-dtypes==1.0.4
debugpy==1.0.0
decorator==4.4.2
defusedxml==0.7.1
desc

numpy datatype : ndarry, matrix  
pandas datatype : Series, DataFrame

구글 드라이브 연동

In [6]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/python_demo

Mounted at /content/drive
/content/drive/MyDrive/python_demo


### 파일 형식 데이터 불러오기

In [11]:
# 읽어오는 파일에 컬럼명이 없으면 header=None을 설정한다.
# 그렇지 않으면 첫번째 줄을 컬럼명으로 인식을 하기 때문이다.
# header파라미터의 default:'infer'
data = pd.read_csv('pdsample/num.txt', header=None)
data

NotADirectoryError: ignored

In [ ]:
type(data)

In [8]:
# 컬럼(열)
print(data[0])
print(type(data[0]))

NameError: ignored

In [ ]:
# index(행)
print(data.iloc[0])
print(type(data.iloc[0])) # Series

0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
# numpy 참고
a = np.arange(12).reshape(3,4)
print(a)
print(a[1][2])
print(a[1])
print(a[1,2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[4 5 6 7]
[6 7]


In [ ]:
# python list 참고
b = [[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11]]
print(b[1][2])
print(b[1])
# print(b[1, 2:])  # list에서는 슬라이싱 안됨

6
[4, 5, 6, 7]


In [ ]:
# .values하면 numpy 포맷으로 변환한다.
# 내부적으로 numpy로 되어 있기 때문에 가능하다.
print(data.values)
print(type(data.values))
data.values


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# __array__가 있으면 numpy와 호환된다.
dir(data)

### 웹 주소에서 데이터 불러오기

In [ ]:
# header은 기본이 첫줄을 컬럼명으로 가져오도록 설정이 되여 있기 때문에 header='infer' 생락 가능하다.
data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv' ,header='infer')
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
# 전반적인 데이터 정보 확인
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [ ]:
# 기본적으로 앞의 5개를 보여줌
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
# 마지막 5개 보여줌
data.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
# random으로 1개씩 보여줌
data.sample()

total_bill  tip     sex smoker  day    time  size
73       25.28  5.0  Female    Yes  Sat  Dinner     2

In [ ]:
# 보여줄 갯수를 지정할 수 있음
#data.head(10)
#data.tail(10)
data.sample(10)

total_bill   tip     sex smoker   day    time  size
178        9.60  4.00  Female    Yes   Sun  Dinner     2
90        28.97  3.00    Male    Yes   Fri  Dinner     2
43         9.68  1.32    Male     No   Sun  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
127       14.52  2.00  Female     No  Thur   Lunch     2
177       14.48  2.00    Male    Yes   Sun  Dinner     2
193       15.48  2.02    Male    Yes  Thur   Lunch     2
111        7.25  1.00  Female     No   Sat  Dinner     1
231       15.69  3.00    Male    Yes   Sat  Dinner     3
80        19.44  3.00    Male    Yes  Thur   Lunch     2

In [ ]:
# 데이터만 가져옴
data.values

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [ ]:
data.index

RangeIndex(start=0, stop=244, step=1)

In [ ]:
data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
# dict 타입
dictdata = {'name':'홍길동', 'age':'30'}
# dictdata.name
dictdata['name']


'홍길동'

In [ ]:
dir(dict)
dict.items

<method 'items' of 'dict' objects>

In [ ]:
# pandas는 dictionary와 attribute 방식 모두 가져올 수 있다.
# dictionary 방식 이용
data['tip']
data['tip'][2]

3.5

In [ ]:
# attribute 방식 이용
data.tip

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [ ]:
#KeyError
# 컬럼을 fancying indexing을 이용해서 가져올 때 index을 이용해서 가져올 수 있다.
#data[[0, 2]]

data[['tip','day']]

tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]

In [ ]:
# TypeError발생
# 컬럼을 slicing을 이용해서 가져올 수 없다.
#data['tip':'day']

# row를 slicing을 이용해서 가져올때는 index을 이용해서 가져온다.
data[1:3] 

total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3

In [ ]:
# KeyError     
#data[3]

data.iloc[3] # indexing

total_bill     23.68
tip             3.31
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 3, dtype: object

하나의 컬럼 또는 행 가져오면 Series로 리턴한다.  
fancy indexing을 이용해서 하나의 컬럼 또는 행을 가져오면 DataFrame으로 리턴한다.

In [ ]:
type(data.iloc[3])

pandas.core.series.Series

In [ ]:
type(data['tip'])  #Series
#type(data.tip)    #Series

pandas.core.series.Series

In [ ]:
type(data[['tip']]) #DataFrame

pandas.core.frame.DataFrame

In [ ]:
data.iloc[0:5]
data.iloc[0:5, :]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
data.iloc[[0, 3, 5]] #fancy indexing    data[['tip','smoker', 'day']]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
3       23.68  3.31    Male     No  Sun  Dinner     2
5       25.29  4.71    Male     No  Sun  Dinner     4

In [ ]:
# 3행 1열
data.iloc[3][1]  #list :  a[3][1]  # array  : a[3,1]

3.31

In [ ]:

data.iloc[0:3, 1:4]

tip     sex smoker
0  1.01  Female     No
1  1.66    Male     No
2  3.50    Male     No

In [ ]:
data.iloc[[0,3,5], [1,4,5]]

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

iloc는 indexer을 이용해서 가져오고, loc를 이름을 이용해서 가져온다.

In [ ]:
# 행은 이름이 설정되여 있지 않아서 자동으로 생성된 Range Index가 이름이 된다.
data.loc[0, 'tip']

1.01

In [ ]:
data.loc[0:5, 'tip':'time']

tip     sex smoker  day    time
0  1.01  Female     No  Sun  Dinner
1  1.66    Male     No  Sun  Dinner
2  3.50    Male     No  Sun  Dinner
3  3.31    Male     No  Sun  Dinner
4  3.61  Female     No  Sun  Dinner
5  4.71    Male     No  Sun  Dinner

In [ ]:
data.loc[[0, 3, 5], ['tip', 'day', 'time']]

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

### at
이름으로 한 위치의 값만 가져온다.

In [ ]:
data.at[0, 'tip']
#data.loc[0, 'tip']
#data.iloc[0, 1]

1.01

In [ ]:
# at은 slicing을 사용할 수 없다.
#data.at[0:3, 'tip']

TypeError: ignored

In [ ]:
# at은 fancying indexing을 사용할 수 없다.
data.at[[1,3,5],['tip','smoker', 'day']]

TypeError: ignored

### iat
iat은 인덱스 번호로 한 위치의 값을 가져온다.

In [ ]:
data.iat[0,1]
#data.at[0,'tip']

In [ ]:
#iat은 슬라이싱을 사용할 수 없다.
data.iat[0:3, 1]

ValueError: ignored

### boolean indexing

In [ ]:
# data.tip >= 5
data['tip'] >= 5


0      False
1      False
2      False
3      False
4      False
       ...  
239     True
240    False
241    False
242    False
243    False
Name: tip, Length: 244, dtype: bool

In [ ]:
data[data['tip'] >= 5]  #data[True, False,True,True.....]

total_bill    tip     sex smoker   day    time  size
11        35.26   5.00  Female     No   Sun  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
73        25.28   5.00  Female    Yes   Sat  Dinner     2
83        32.68   5.00    Male    Yes  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
185       20.69   5.00    Male     No   Sun  Dinner     5
197       43.11   5.00  Female    Yes  Thur   Lunch     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [ ]:
data.tip
data['tip']
#a = data[data['tip']>=5]
#a['tip']

data[data['tip']>=5]['tip'] # data[data['tip']>=5]의 결과는 DataFrame
#data['tip'][3]             # data['tip']의 결과는 Series


3.31

In [ ]:
data[data['tip']>=5].loc[:, 'tip':'day']

tip     sex smoker   day
11    5.00  Female     No   Sun
23    7.58    Male     No   Sat
39    5.00    Male     No   Sat
44    5.60    Male     No   Sun
46    5.00    Male     No   Sun
47    6.00    Male     No   Sun
52    5.20  Female     No   Sun
59    6.73    Male     No   Sat
73    5.00  Female    Yes   Sat
83    5.00    Male    Yes  Thur
85    5.17  Female     No  Thur
88    5.85    Male     No  Thur
116   5.07    Male     No   Sun
141   6.70    Male     No  Thur
142   5.00    Male     No  Thur
143   5.00  Female     No  Thur
155   5.14  Female     No   Sun
156   5.00    Male     No   Sun
170  10.00    Male    Yes   Sat
172   5.15    Male    Yes   Sun
181   5.65    Male    Yes   Sun
183   6.50    Male    Yes   Sun
185   5.00    Male     No   Sun
197   5.00  Female    Yes  Thur
211   5.16    Male    Yes   Sat
212   9.00    Male     No   Sat
214   6.50  Female    Yes   Sat
239   5.92    Male     No   Sat

In [ ]:
data[data['tip']>=5].iloc[:, 1:5]

tip     sex smoker   day
11    5.00  Female     No   Sun
23    7.58    Male     No   Sat
39    5.00    Male     No   Sat
44    5.60    Male     No   Sun
46    5.00    Male     No   Sun
47    6.00    Male     No   Sun
52    5.20  Female     No   Sun
59    6.73    Male     No   Sat
73    5.00  Female    Yes   Sat
83    5.00    Male    Yes  Thur
85    5.17  Female     No  Thur
88    5.85    Male     No  Thur
116   5.07    Male     No   Sun
141   6.70    Male     No  Thur
142   5.00    Male     No  Thur
143   5.00  Female     No  Thur
155   5.14  Female     No   Sun
156   5.00    Male     No   Sun
170  10.00    Male    Yes   Sat
172   5.15    Male    Yes   Sun
181   5.65    Male    Yes   Sun
183   6.50    Male    Yes   Sun
185   5.00    Male     No   Sun
197   5.00  Female    Yes  Thur
211   5.16    Male    Yes   Sat
212   9.00    Male     No   Sat
214   6.50  Female    Yes   Sat
239   5.92    Male     No   Sat

In [ ]:
data[data['tip']>=5][['tip','day']]

tip   day
11    5.00   Sun
23    7.58   Sat
39    5.00   Sat
44    5.60   Sun
46    5.00   Sun
47    6.00   Sun
52    5.20   Sun
59    6.73   Sat
73    5.00   Sat
83    5.00  Thur
85    5.17  Thur
88    5.85  Thur
116   5.07   Sun
141   6.70  Thur
142   5.00  Thur
143   5.00  Thur
155   5.14   Sun
156   5.00   Sun
170  10.00   Sat
172   5.15   Sun
181   5.65   Sun
183   6.50   Sun
185   5.00   Sun
197   5.00  Thur
211   5.16   Sat
212   9.00   Sat
214   6.50   Sat
239   5.92   Sat

요일이 'Sun' 이거나 'Sat'의 tip과 day의 값의 가져오기

In [ ]:
data[(data['day']=='Sun') | (data['day']=='Sat')][['tip', 'day']]

a = data[(data['day']=='Sun') | (data['day']=='Sat')]
a['day'].unique()
a[['tip', 'day']]

tip  day
0    1.01  Sun
1    1.66  Sun
2    3.50  Sun
3    3.31  Sun
4    3.61  Sun
..    ...  ...
238  4.67  Sat
239  5.92  Sat
240  2.00  Sat
241  2.00  Sat
242  1.75  Sat

[163 rows x 2 columns]

In [ ]:


#len([1,2,3])
#len('123')
#len({'a':1,'b':2,'c':3})
#len(data)

# [1,2,3].size  #AttributeError
#'123'.size       #AttributeError
#{'a':1,'b':2,'c':3}.size

import numpy as np
(np.array([1,2,3])).size
data.size  # 244 * 7
data['tip'].size
data.tip

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [ ]:
# 컬럼명을 바꿀때 mapper, columns 옵션을 이용해서 변경할 수 있다.
data2 = data.rename(mapper={'size':'size_'}, axis=1)
data2 = data.rename(columns={'size':'size_'})
data2


total_bill   tip     sex smoker   day    time  size_
0         16.99  1.01  Female     No   Sun  Dinner      2
1         10.34  1.66    Male     No   Sun  Dinner      3
2         21.01  3.50    Male     No   Sun  Dinner      3
3         23.68  3.31    Male     No   Sun  Dinner      2
4         24.59  3.61  Female     No   Sun  Dinner      4
..          ...   ...     ...    ...   ...     ...    ...
239       29.03  5.92    Male     No   Sat  Dinner      3
240       27.18  2.00  Female    Yes   Sat  Dinner      2
241       22.67  2.00    Male    Yes   Sat  Dinner      2
242       17.82  1.75    Male     No   Sat  Dinner      2
243       18.78  3.00  Female     No  Thur  Dinner      2

[244 rows x 7 columns]

In [ ]:
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Category


In [3]:
data.info()

NameError: ignored

In [10]:
print(data['sex']).dtype)

SyntaxError: ignored

In [12]:
data.sample()

NameError: ignored