<a href="https://colab.research.google.com/github/kimberlyydanij/python_demo/blob/master/python_12_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 6. 3차원 이상에서 차원 구분법

In [1]:
import numpy as np

In [2]:
b = np.arange(24).reshape(2,3,4)

In [ ]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
print(b)   
# print 하면 ### array라는 글자는 안보인다 
# 공백은 그대로 보이므로 차원 구분 가능하다

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
b[0,1]

array([4, 5, 6, 7])

In [ ]:
b[1,1]

array([16, 17, 18, 19])

In [ ]:
b[0,1,3]

7

### 7. Fancy indexing과 indexing의 차이
- indexing은 원래 차원에서 하나 감소해서 가져오고 ,fancy indexing은 원래 차원 그대로 가져온다

In [ ]:
# indexing은 차원이 하나 감소해서 가져온다. (3차원 -> 2차원)
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# fancy indexing은 원래 3차원 그대로 가지고 온다.
b[[0]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [ ]:
# b[0]은 b[0.:,:]의 단축 표현이다
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# b의 0번째 공간, 1번째 행 미만, 열 전체
b[0, :1, :]

array([[0, 1, 2, 3]])

### 8 Ellipsis
...(Ellipsis)는 이후로 모든것을 의미한다.

In [ ]:
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0] # 생략기법
b[0,:,:] # slicing 기법
b[0,...] # ellipsis 기법

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 숫자 1,5,9만 가져온다
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b[0,:,1]

array([1, 5, 9])

In [3]:
# 숫자 1,5,9,3,7,11 가져오기
b[0,:,(1,3)]
b[0,:,[1,3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [13]:
#숫자 4,5,6,7,16,17,18,19 가져오기
b[:,1,:]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [14]:
b[:,1:2,:]

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [17]:
#숫자 3,7,11,15,19,23
b[:,:,3]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [18]:
b[:,:,-1]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [19]:
b[:,:,3:4]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [20]:
b[:,:,[3]]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

In [22]:
c = b[:,:,3]
c.shape

(2, 3)

### 줄임표현(...)
출력해야할 데이터 수가 엄청 클 때보이는 ...는 Ellipsis와 다르다.

In [23]:
# out에 나오는 ...은 단순히 줄임 표현이다
np.arange(100000)

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [25]:
np.set_printoptions(edgeitems=6)

In [26]:
np.arange(100000)

array([    0,     1,     2,     3,     4,     5, ..., 99994, 99995, 99996,
       99997, 99998, 99999])

#9. 연산
numpy 연산의 기본은 두개의 shape가 같아야 한다

In [27]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a.shape

(3, 4)

In [29]:
b = np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
#같은 위치의 원소끼리 더해준다(elementwise)
a+b

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

numpy는 elementwise로 vectorize연산을 한다.
vectorize는 데이터의 연산을 일괄적으로 처리하는 기능이다.


In [31]:
#python의 list 에서 + 연산자는 elementwise가 아니라 list를 확장시킨다. (연결)
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [32]:
@np.vectorize
def plus(a,b) :
  return a+b

plus([1,2,3], [4,5,6])  #elementwise(요소들끼리 계산하는 것), vectorize

array([5, 7, 9])

In [33]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
b = np.arange(6, 12).reshape(2,3)

In [35]:
a*b

array([[ 0,  7, 16],
       [27, 40, 55]])

In [36]:
#python의 list끼리 * (곱하기)를 할 수 없다.
[1, 2, 3] * [4, 5, 6] 

TypeError: ignored

In [37]:
type(np.array(3))

numpy.ndarray

In [38]:
c = np.matrix([[1,2],[3,4]])
c

matrix([[1, 2],
        [3, 4]])

In [40]:
type(c)

numpy.matrix

numpy에소는 ndarry이외에 matrix라는 자료형도 존재한다.
matrix에서는 * 연산자는 행렬곱을 의미한다.

In [41]:
# matrix * matrix = 행렬곱
# 1*1+2*3  1*2+2*4
# 3*1+4*3  3*2+4*4
c * c

matrix([[ 7, 10],
        [15, 22]])

ndarry에서 행렬곱 연산자 @이다.
python 재단에서 numpy를 위해 만들어준 연산자이다.

In [42]:
a.shape

(2, 3)

In [43]:
b.shape

(2, 3)

In [45]:
a @ b

ValueError: ignored

행렬 곱을 하기 위해서는 shape가 맞아야 한다. 
T는 transpost(전치)의 약자이다.

In [46]:
# 전치 행렬 : 행과 열을 바꾼다.
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [48]:
 a @ a.T

array([[ 5, 14],
       [14, 50]])

In [49]:
np.dot(a, a.T) #ndarry

array([[ 5, 14],
       [14, 50]])

AttributeError: ignored

method방법으로도 행렬곱 할 수 있다.
function 방법과 사용하는 방법이 다르므로 주의한다.

In [51]:
np.dot(a,a.T)  #function 방식

array([[ 5, 14],
       [14, 50]])

In [52]:
a.dot(a.T)  #method 방식

array([[ 5, 14],
       [14, 50]])

### 10. Broadcasting
python은 배열과 숫자간에 연산을 할 수 있다.

[1,2,3] + 1 (x)
[1,2,3] + [1,2,3] (0)
[1,2,3] * 1 (0) => 반복
[1,2,3] * [1,2,3] => (x)

In [57]:
a = np.arange(6).reshape(2,3)   #adarry
a

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
a + 1

array([[1, 2, 3],
       [4, 5, 6]])

# broadcating 이란 모양이 같지 않아도, 특정한 조건에 부합하면 모양을 같게 만들어 연산하는 기능이다.
위 연산에서 1을 a와 같은 모양으로 만들어 계산한다.

### (1) broadcasting이 되는 경우와 안되는 경우

In [59]:
a  #2행 3열

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
a + np.array([3,4])

ValueError: ignored

In [61]:
a + np.array([3,4,5])

array([[ 3,  5,  7],
       [ 6,  8, 10]])

In [64]:
a + np.array([[1],[2]])

array([[1, 2, 3],
       [5, 6, 7]])

# 11. Strides
strides는 다음 원소끼리 메모리 크기를 차원별로 알려준다.
c의 포인터 개념을 알고 있으면 이해하기가 쉽다.

In [68]:
a = np.arange(12).reshape(3,4)

In [69]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
#  행의 메모리 간격은 32bytes, 열의 메모리 간격은 4bytes
a.strides

(32, 8)

In [71]:
a.dtype

dtype('int64')

In [72]:
a.itemsize

8

In [73]:
# 열의 원소 개수 * itemzise =  행의 메모리 간격
# itemsize = 열의 메모리 간격
a.shape

(3, 4)

# 12. axis
axis는 다차원 배열을 연산할때 기준이 되는 축이다.


In [74]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
np.sum(a)

66

In [76]:
np.sum(a, axis=0) # a배열은 2차원 이므로 axis=0은 행기준(행마다)

array([12, 15, 18, 21])

In [77]:
np.sum(a, axis=1) #a배열은 2차원이므로 axis = 1은 열기준(열마다)

array([ 6, 22, 38])

axis는 3차원 이상에서도 사용할 수 있다.

In [78]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [79]:
#a.sum(axis=0)
np.sum(a, axis=0) # 공간 기준(공간 마다)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [80]:
#a.sum(axis=1)
np.sum(a, axis=1) # 행 기준(행 마다)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [81]:
#a.sum(axis=2)
np.sum(a, axis=2) #열 기준(열 마다)

array([[ 6, 22, 38],
       [54, 70, 86]])

3차원은 행렬에 공간(깊이) 개념이 추가되었다고 할 수 있다.
2차원(axis = 0, axis=1)(행,열)
3차원(axis = 0, axis=1, axis=2)(공간, 행, 열)

# 12. array 모양 바꾸기

(1) reshape
reshpae는 차원을 바꿔주는 기능을 한다.

In [83]:
a = np.arange(24).reshape(3,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [84]:
# signature대로 하면 a.reshape((3,8)) 해야 한다.
# 하지만 reshape(3,8) 해도 내부적으로 이상없이 처리한다.
# reshape 수행 후의 값은 그대로 있다.
a = np.arange(24)
b = a.reshape(3,8)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [85]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [86]:
a = np.arange(24).reshape(3,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [87]:
a.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [89]:
# ValueError   크기가 맞지 않음
a.reshape(2,3,5)

ValueError: ignored

In [93]:
#마지막 값을 음수값을 주면(어떤 수던 상관 없음), 알아서 맞춤
a.reshape(2,3,-100)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [94]:
a.reshape(3,5,-1)

ValueError: ignored

In [95]:
# 음수값은 2개 사용할 수 없다.
# 음수 값은 다른 차원들이 정해 진 상황에서 남은 하나의 차원만 알아서 맞춰준다.
a.reshape(3,-1,-1)

ValueError: ignored

In [96]:
a.reshape(3,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

#(2) reshape로 차원 늘리기

In [98]:
# 2차원
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [99]:
# 3차원
a = np.arange(6).reshape(2,3,1)
a

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

# 13. resize
size는 원소 개수를 알려준다.

In [100]:
a = np.arange(24)
print(a.size)

24


In [102]:
#a.resize(2,3,1)
np.resize(a,(2,3,1))

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [103]:
np.resize(a, (3,2,8))

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23],
        [ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]])

In [105]:
#빈 공간은 0으로 채워줌
b = np.arange(24)
b.resize((2,3,8))
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]]])

### array 쪼개기
 

---

